version: "3.7"
services:
  auth-api:
    image: registry.digitalocean.com/magnus-images/other:messaging-service-0.1.0
    env_file: '.env'
    container_name: messaging-service
    networks:
      - social-app
    restart: unless-stopped

networks:
  social-app:
    external: true
